### ISSUE TITLE
Crash when decompressing JSON string

### ISSUE THREAD

**Issue by dsidirop** [4kills/zlib#8] opened 2022-03-18 16:46 UTC
I have the following compressor / decompressor combo:

    zlibCompressorFactory := func(compressionLevel int) func(rawBytes []byte) ([]byte, error) {
		return func(rawBytes []byte) ([]byte, error) {
			compressedBytesBufferWriter := &bytes.Buffer{}

			zlibCompressor, err := zlib.NewWriterLevel(compressedBytesBufferWriter, compressionLevel)
			if err != nil {
				return nil, err
			}

			_, err = zlibCompressor.Write(rawBytes)
			zlibCompressor.Close() //dont use defer   it wont work

			if err != nil {
				return nil, err
			}

			return compressedBytesBufferWriter.Bytes(), err
		}
	}
	zlibDecompressorFactory := func() func(compressedBytes []byte) ([]byte, error) {
		return func(compressedBytes []byte) ([]byte, error) {
			compressedInputBuffer := bytes.NewReader(compressedBytes)

			zlibDecompressor, err := zlib.NewReader(compressedInputBuffer)
			if err != nil {
				return nil, err
			}

			decompressedBytes, err := ioutil.ReadAll(zlibDecompressor)
			zlibDecompressor.Close()

			if err != nil {
				return nil, err
			}

			return decompressedBytes, nil
		}
	}
	
But when trying to decompress I get the following error - this doesn't happen with "common/zlib" it only happens with "go-zlib" (tested with both golang 1.17 and 1.18):

Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^Benchmark___DecompressionAndDeserializationPerformance___Json$ github.com/klauspost/compress/arena/bb-decompression-deserialization-performance

goos: linux
panic: runtime error: slice bounds out of range [:1034] with capacity 896

goroutine 21 [running]:
io.ReadAll({0xbae4e0, 0xc0002208d0})
	/usr/local/go/src/io/io.go:646 +0x197
io/ioutil.ReadAll(...)
	/usr/local/go/src/io/ioutil/ioutil.go:27
github.com/klauspost/compress/arena.InitCompressionTestCases.func2.1({0xc000382000, 0x2d3, 0x351})
	/mnt/c/VS/laerdal/magellan-serialization-and-compression-benchmarks-testbed/arena/initialize-alternative-datasources-from-main-datasource.go:210 +0x9f
github.com/klauspost/compress/arena/bb-decompression-deserialization-performance.Benchmark___DecompressionAndDeserializationPerformance___Json.func1(0xc0001f6240)
	/mnt/c/VS/laerdal/magellan-serialization-and-compression-benchmarks-testbed/arena/bb-decompression-deserialization-performance/xaa_json_test.go:40 +0x3c3
testing.(*B).runN(0xc0001f6240, 0x1)
	/usr/local/go/src/testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
	/usr/local/go/src/testing/benchmark.go:233 +0x59
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:226 +0x9c
exit status 2
FAIL	github.com/klauspost/compress/arena/bb-decompression-deserialization-performance	0.018s
FAIL

What gives?

**Comment by 4kills** [comment] 2022-06-28 07:27
Sorry for the late reply. Perhaps this was fixed in #9 ?

**Comment by 4kills** [comment] 2024-01-18 18:49
Due to inactivity and a wrong strack trace (not including this library?) as well as missing tests, I can not reproduce the error. This is why I am closing the issue now

**Closed as not planned by 4kills** 2024-01-18 18:49 UTC
